use coolc::{
    lexer::{ErrorKind, ErrorToken, LexerExtras, Token},
    string_table::StringTable,
};
use logos::Logos;

fn lex(src: &str) -> Vec<Token> {
    let mut s_table = StringTable::new();
    Token::lexer_with_extras(
        src,
        LexerExtras {
            s_table: &mut s_table,
            file: String::from("test"),
        },
    )
    .map(|r| r.unwrap_or_else(|e| Token::Err(e)))
    .collect()
}

mod succeeds_lexing {
    use super::*;

    #[test]
    fn test_integer() {
        assert_eq!(lex("123"), vec![Token::Integers(123)]);
    }

    #[test]
    fn nested_comments() {
        assert_eq!(lex("(*(*(*(**)*)*)*)"), vec![]);
    }

    #[test]
    fn hello_world_string() {
        let src = "\"Hello World!\"";
        let mut s_table = StringTable::new();
        let mut lex = Token::lexer_with_extras(
            src,
            LexerExtras {
                s_table: &mut s_table,
                file: String::from("test"),
            },
        );

        let tok = lex.next().unwrap().unwrap();
        let Token::StringConstant(id) = tok else {
            panic!("expected StringConstant")
        };
        assert_eq!(
            lex.extras.s_table.string_from_id(id).unwrap(),
            "Hello World!"
        );
    }

    #[test]
    fn cool_cl() {
        let src = include_str!("../examples/cool.cl");
        let mut s_table = StringTable::new();
        let mut lexer = Token::lexer_with_extras(
            src,
            LexerExtras {
                s_table: &mut s_table,
                file: String::from("test"),
            },
        );
        let tokens: Vec<Token> = lexer.by_ref().map(|t| t.unwrap()).collect();
        let table = &lexer.extras.s_table;
        let expected = vec![
            Token::Class,
            Token::TypeIdentifier(table.lookup("Main").unwrap()),
            Token::Inherits,
            Token::TypeIdentifier(table.lookup("IO").unwrap()),
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("main").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::LParen,
            Token::New,
            Token::TypeIdentifier(table.lookup("Object").unwrap()),
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(table.lookup("type_name").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(table.lookup("substr").unwrap()),
            Token::LParen,
            Token::Integers(4),
            Token::Comma,
            Token::Integers(1),
            Token::RParen,
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::LParen,
            Token::IsVoid,
            Token::SelfValue,
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(table.lookup("type_name").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(table.lookup("substr").unwrap()),
            Token::LParen,
            Token::Integers(1),
            Token::Comma,
            Token::Integers(3),
            Token::RParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::RBrace,
            Token::RBrace,
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
        ];

        assert_eq!(tokens, expected);
    }

    #[test]
    fn primes_cl() {
        let src = include_str!("../examples/primes.cl");
        let mut s_table = StringTable::new();
        let mut lexer = Token::lexer_with_extras(
            src,
            LexerExtras {
                s_table: &mut s_table,
                file: String::from("test"),
            },
        );
        let tokens: Vec<Token> = lexer.by_ref().map(|t| t.unwrap()).collect();
        let table = &lexer.extras.s_table;

        let expected: Vec<Token> = vec![
            Token::Class,
            Token::TypeIdentifier(table.lookup("Main").unwrap()),
            Token::Inherits,
            Token::TypeIdentifier(table.lookup("IO").unwrap()),
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("main").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::LBrace,
            Token::Integers(0),
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::Assign,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("2 is trivially prime.\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::Integers(2),
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("testee").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("out").unwrap()),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("divisor").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("stop").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::Assign,
            Token::Integers(500),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("m").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Object").unwrap()),
            Token::Assign,
            Token::While,
            Token::BoolConst(true),
            Token::Loop,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("testee").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("testee").unwrap()),
            Token::Plus,
            Token::Integers(1),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("divisor").unwrap()),
            Token::Assign,
            Token::Integers(2),
            Token::Semicolon,
            Token::While,
            Token::If,
            Token::ObjectIdentifier(table.lookup("testee").unwrap()),
            Token::Lt,
            Token::ObjectIdentifier(table.lookup("divisor").unwrap()),
            Token::Star,
            Token::ObjectIdentifier(table.lookup("divisor").unwrap()),
            Token::Then,
            Token::BoolConst(false),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("testee").unwrap()),
            Token::Minus,
            Token::ObjectIdentifier(table.lookup("divisor").unwrap()),
            Token::Star,
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("testee").unwrap()),
            Token::Slash,
            Token::ObjectIdentifier(table.lookup("divisor").unwrap()),
            Token::RParen,
            Token::Eq,
            Token::Integers(0),
            Token::Then,
            Token::BoolConst(false),
            Token::Else,
            Token::BoolConst(true),
            Token::Fi,
            Token::Fi,
            Token::Loop,
            Token::ObjectIdentifier(table.lookup("divisor").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("divisor").unwrap()),
            Token::Plus,
            Token::Integers(1),
            Token::Pool,
            Token::Semicolon,
            Token::If,
            Token::ObjectIdentifier(table.lookup("testee").unwrap()),
            Token::Lt,
            Token::ObjectIdentifier(table.lookup("divisor").unwrap()),
            Token::Star,
            Token::ObjectIdentifier(table.lookup("divisor").unwrap()),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("out").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("testee").unwrap()),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_int").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("out").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup(" is prime.\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::RBrace,
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Semicolon,
            Token::If,
            Token::ObjectIdentifier(table.lookup("stop").unwrap()),
            Token::Le,
            Token::ObjectIdentifier(table.lookup("testee").unwrap()),
            Token::Then,
            Token::StringConstant(table.lookup("halt").unwrap()),
            Token::Dot,
            Token::ObjectIdentifier(table.lookup("abort").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Else,
            Token::StringConstant(table.lookup("continue").unwrap()),
            Token::Fi,
            Token::Semicolon,
            Token::RBrace,
            Token::Pool,
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
        ];

        assert_eq!(tokens, expected);
    }

    #[test]
    fn life_cl() {
        let src = include_str!("../examples/life.cl");
        let mut s_table = StringTable::new();
        let mut lexer = Token::lexer_with_extras(
            src,
            LexerExtras {
                s_table: &mut s_table,
                file: String::from("test"),
            },
        );
        let tokens: Vec<Token> = lexer.by_ref().map(|t| t.unwrap()).collect();
        let table = &lexer.extras.s_table;

        let expected: Vec<Token> = vec![
            Token::Class,
            Token::TypeIdentifier(table.lookup("Board").unwrap()),
            Token::Inherits,
            Token::TypeIdentifier(table.lookup("IO").unwrap()),
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("rows").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("board_size").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("size_of_board").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("initial").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("initial").unwrap()),
            Token::Dot,
            Token::ObjectIdentifier(table.lookup("length").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("board_init").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("start").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.lookup("size").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("size_of_board").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("start").unwrap()),
            Token::RParen,
            Token::In,
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(table.lookup("size").unwrap()),
            Token::Eq,
            Token::Integers(15),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("rows").unwrap()),
            Token::Assign,
            Token::Integers(3),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::Assign,
            Token::Integers(5),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("board_size").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("size").unwrap()),
            Token::Semicolon,
            Token::RBrace,
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("size").unwrap()),
            Token::Eq,
            Token::Integers(16),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("rows").unwrap()),
            Token::Assign,
            Token::Integers(4),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::Assign,
            Token::Integers(4),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("board_size").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("size").unwrap()),
            Token::Semicolon,
            Token::RBrace,
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("size").unwrap()),
            Token::Eq,
            Token::Integers(20),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("rows").unwrap()),
            Token::Assign,
            Token::Integers(4),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::Assign,
            Token::Integers(5),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("board_size").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("size").unwrap()),
            Token::Semicolon,
            Token::RBrace,
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("size").unwrap()),
            Token::Eq,
            Token::Integers(21),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("rows").unwrap()),
            Token::Assign,
            Token::Integers(3),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::Assign,
            Token::Integers(7),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("board_size").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("size").unwrap()),
            Token::Semicolon,
            Token::RBrace,
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("size").unwrap()),
            Token::Eq,
            Token::Integers(25),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("rows").unwrap()),
            Token::Assign,
            Token::Integers(5),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::Assign,
            Token::Integers(5),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("board_size").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("size").unwrap()),
            Token::Semicolon,
            Token::RBrace,
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("size").unwrap()),
            Token::Eq,
            Token::Integers(28),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("rows").unwrap()),
            Token::Assign,
            Token::Integers(7),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::Assign,
            Token::Integers(4),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("board_size").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("size").unwrap()),
            Token::Semicolon,
            Token::RBrace,
            Token::Else,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("rows").unwrap()),
            Token::Assign,
            Token::Integers(5),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::Assign,
            Token::Integers(5),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("board_size").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("size").unwrap()),
            Token::Semicolon,
            Token::RBrace,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Semicolon,
            Token::SelfValue,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
            Token::Class,
            Token::TypeIdentifier(table.lookup("CellularAutomaton").unwrap()),
            Token::Inherits,
            Token::TypeIdentifier(table.lookup("Board").unwrap()),
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("population_map").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("init").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("map").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("population_map").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("map").unwrap()),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("board_init").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("map").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::SelfValue,
            Token::Semicolon,
            Token::RBrace,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("print").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.lookup("i").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::Assign,
            Token::Integers(0),
            Token::In,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("board_size").unwrap()),
            Token::In,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::While,
            Token::ObjectIdentifier(table.lookup("i").unwrap()),
            Token::Lt,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Loop,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("population_map").unwrap()),
            Token::Dot,
            Token::ObjectIdentifier(table.lookup("substr").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("i").unwrap()),
            Token::Comma,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("i").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("i").unwrap()),
            Token::Plus,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::Semicolon,
            Token::RBrace,
            Token::Pool,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::SelfValue,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("num_cells").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("population_map").unwrap()),
            Token::Dot,
            Token::ObjectIdentifier(table.lookup("length").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("cell").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(table.lookup("board_size").unwrap()),
            Token::Minus,
            Token::Integers(1),
            Token::Lt,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Then,
            Token::StringConstant(table.lookup(" ").unwrap()),
            Token::Else,
            Token::ObjectIdentifier(table.lookup("population_map").unwrap()),
            Token::Dot,
            Token::ObjectIdentifier(table.lookup("substr").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Comma,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("north").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::LBrace,
            Token::If,
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Minus,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Lt,
            Token::Integers(0),
            Token::Then,
            Token::StringConstant(table.lookup(" ").unwrap()),
            Token::Else,
            Token::ObjectIdentifier(table.lookup("cell").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Minus,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("south").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(table.lookup("board_size").unwrap()),
            Token::Lt,
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Plus,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Then,
            Token::StringConstant(table.lookup(" ").unwrap()),
            Token::Else,
            Token::ObjectIdentifier(table.lookup("cell").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Plus,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("east").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::LBrace,
            Token::If,
            Token::LParen,
            Token::LParen,
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Slash,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Star,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Eq,
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Then,
            Token::StringConstant(table.lookup(" ").unwrap()),
            Token::Else,
            Token::ObjectIdentifier(table.lookup("cell").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("west").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Eq,
            Token::Integers(0),
            Token::Then,
            Token::StringConstant(table.lookup(" ").unwrap()),
            Token::Else,
            Token::If,
            Token::LParen,
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Slash,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Star,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Eq,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Then,
            Token::StringConstant(table.lookup(" ").unwrap()),
            Token::Else,
            Token::ObjectIdentifier(table.lookup("cell").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Minus,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("northwest").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::LBrace,
            Token::If,
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Minus,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Lt,
            Token::Integers(0),
            Token::Then,
            Token::StringConstant(table.lookup(" ").unwrap()),
            Token::Else,
            Token::If,
            Token::LParen,
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Slash,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Star,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Eq,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Then,
            Token::StringConstant(table.lookup(" ").unwrap()),
            Token::Else,
            Token::ObjectIdentifier(table.lookup("north").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Minus,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("northeast").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::LBrace,
            Token::If,
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Minus,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Lt,
            Token::Integers(0),
            Token::Then,
            Token::StringConstant(table.lookup(" ").unwrap()),
            Token::Else,
            Token::If,
            Token::LParen,
            Token::LParen,
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Slash,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Star,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Eq,
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Then,
            Token::StringConstant(table.lookup(" ").unwrap()),
            Token::Else,
            Token::ObjectIdentifier(table.lookup("north").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("southeast").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(table.lookup("board_size").unwrap()),
            Token::Lt,
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Plus,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Then,
            Token::StringConstant(table.lookup(" ").unwrap()),
            Token::Else,
            Token::If,
            Token::LParen,
            Token::LParen,
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Slash,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Star,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Eq,
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Then,
            Token::StringConstant(table.lookup(" ").unwrap()),
            Token::Else,
            Token::ObjectIdentifier(table.lookup("south").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("southwest").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(table.lookup("board_size").unwrap()),
            Token::Lt,
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Plus,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Then,
            Token::StringConstant(table.lookup(" ").unwrap()),
            Token::Else,
            Token::If,
            Token::LParen,
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Slash,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Star,
            Token::ObjectIdentifier(table.lookup("columns").unwrap()),
            Token::RParen,
            Token::Eq,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Then,
            Token::StringConstant(table.lookup(" ").unwrap()),
            Token::Else,
            Token::ObjectIdentifier(table.lookup("south").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Minus,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("neighbors").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::LBrace,
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(table.lookup("north").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(table.lookup("X").unwrap()),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(table.lookup("south").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(table.lookup("X").unwrap()),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(table.lookup("east").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(table.lookup("X").unwrap()),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(table.lookup("west").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(table.lookup("X").unwrap()),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(table.lookup("northeast").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(table.lookup("X").unwrap()),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(table.lookup("northwest").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(table.lookup("X").unwrap()),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(table.lookup("southeast").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(table.lookup("X").unwrap()),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(table.lookup("southwest").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(table.lookup("X").unwrap()),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Semicolon,
            Token::RBrace,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("cell_at_next_evolution").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(table.lookup("neighbors").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::RParen,
            Token::Eq,
            Token::Integers(3),
            Token::Then,
            Token::StringConstant(table.lookup("X").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("neighbors").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::RParen,
            Token::Eq,
            Token::Integers(2),
            Token::Then,
            Token::If,
            Token::ObjectIdentifier(table.lookup("cell").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(table.lookup("X").unwrap()),
            Token::Then,
            Token::StringConstant(table.lookup("X").unwrap()),
            Token::Else,
            Token::StringConstant(table.lookup("-").unwrap()),
            Token::Fi,
            Token::Else,
            Token::StringConstant(table.lookup("-").unwrap()),
            Token::Fi,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("evolve").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::Assign,
            Token::Integers(0),
            Token::In,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("num_cells").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::In,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.lookup("temp").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::In,
            Token::LBrace,
            Token::While,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Lt,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Loop,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("temp").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("temp").unwrap()),
            Token::Dot,
            Token::ObjectIdentifier(table.lookup("concat").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("cell_at_next_evolution").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::RParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("position").unwrap()),
            Token::Plus,
            Token::Integers(1),
            Token::Semicolon,
            Token::RBrace,
            Token::Pool,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("population_map").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("temp").unwrap()),
            Token::Semicolon,
            Token::SelfValue,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::RParen,
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("option").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::LBrace,
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Int").unwrap()),
            Token::In,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\nPlease chose a number:\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t1: A cross\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(
                table
                    .lookup("\t2: A slash from the upper left to lower right\n")
                    .unwrap(),
            ),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(
                table
                    .lookup("\t3: A slash from the upper right to lower left\n")
                    .unwrap(),
            ),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t4: An X\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t5: A greater than sign \n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t6: A less than sign\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t7: Two greater than signs\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t8: Two less than signs\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t9: A 'V'\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t10: An inverse 'V'\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t11: Numbers 9 and 10 combined\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t12: A full grid\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t13: A 'T'\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t14: A plus '+'\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t15: A 'W'\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t16: An 'M'\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t17: An 'E'\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t18: A '3'\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t19: An 'O'\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t20: An '8'\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\t21: An 'S'\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("Your choice => ").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("in_int").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(1),
            Token::Then,
            Token::StringConstant(table.lookup(" XX  XXXX XXXX  XX  ").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(2),
            Token::Then,
            Token::StringConstant(table.lookup("    X   X   X   X   X    ").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(3),
            Token::Then,
            Token::StringConstant(table.lookup("X     X     X     X     X").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(4),
            Token::Then,
            Token::StringConstant(table.lookup("X   X X X   X   X X X   X").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(5),
            Token::Then,
            Token::StringConstant(table.lookup("X     X     X   X   X    ").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(6),
            Token::Then,
            Token::StringConstant(table.lookup("    X   X   X     X     X").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(7),
            Token::Then,
            Token::StringConstant(table.lookup("X  X  X  XX  X      ").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(8),
            Token::Then,
            Token::StringConstant(table.lookup(" X  XX  X  X  X     ").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(9),
            Token::Then,
            Token::StringConstant(table.lookup("X   X X X   X  ").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(10),
            Token::Then,
            Token::StringConstant(table.lookup("  X   X X X   X").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(11),
            Token::Then,
            Token::StringConstant(table.lookup("X X X X X X X X").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(12),
            Token::Then,
            Token::StringConstant(table.lookup("XXXXXXXXXXXXXXXXXXXXXXXXX").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(13),
            Token::Then,
            Token::StringConstant(table.lookup("XXXXX  X    X    X    X  ").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(14),
            Token::Then,
            Token::StringConstant(table.lookup("  X    X  XXXXX  X    X  ").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(15),
            Token::Then,
            Token::StringConstant(table.lookup("X     X X X X   X X  ").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(16),
            Token::Then,
            Token::StringConstant(table.lookup("  X X   X X X X     X").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(17),
            Token::Then,
            Token::StringConstant(table.lookup("XXXXX   X   XXXXX   X   XXXX").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(18),
            Token::Then,
            Token::StringConstant(table.lookup("XXX    X   X  X    X   XXXX ").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(19),
            Token::Then,
            Token::StringConstant(table.lookup(" XX X  XX  X XX ").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(20),
            Token::Then,
            Token::StringConstant(table.lookup(" XX X  XX  X XX X  XX  X XX ").unwrap()),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.lookup("num").unwrap()),
            Token::Eq,
            Token::Integers(21),
            Token::Then,
            Token::StringConstant(table.lookup(" XXXX   X    XX    X   XXXX ").unwrap()),
            Token::Else,
            Token::StringConstant(table.lookup("                         ").unwrap()),
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::Semicolon,
            Token::RBrace,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("prompt").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Bool").unwrap()),
            Token::LBrace,
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.lookup("ans").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::In,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(
                table
                    .lookup("Would you like to continue with the next generation? \n")
                    .unwrap(),
            ),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(
                table
                    .lookup("Please use lowercase y or n for your answer [y]: ")
                    .unwrap(),
            ),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("ans").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("in_string").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::If,
            Token::ObjectIdentifier(table.lookup("ans").unwrap()),
            Token::Eq,
            Token::StringConstant(table.lookup("n").unwrap()),
            Token::Then,
            Token::BoolConst(false),
            Token::Else,
            Token::BoolConst(true),
            Token::Fi,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::Semicolon,
            Token::RBrace,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("prompt2").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Bool").unwrap()),
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.lookup("ans").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::In,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("\n\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(
                table
                    .lookup("Would you like to choose a background pattern? \n")
                    .unwrap(),
            ),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(
                table
                    .lookup("Please use lowercase y or n for your answer [n]: ")
                    .unwrap(),
            ),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("ans").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("in_string").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::If,
            Token::ObjectIdentifier(table.lookup("ans").unwrap()),
            Token::Eq,
            Token::StringConstant(table.lookup("y").unwrap()),
            Token::Then,
            Token::BoolConst(true),
            Token::Else,
            Token::BoolConst(false),
            Token::Fi,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
            Token::Class,
            Token::TypeIdentifier(table.lookup("Main").unwrap()),
            Token::Inherits,
            Token::TypeIdentifier(table.lookup("CellularAutomaton").unwrap()),
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("cells").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("CellularAutomaton").unwrap()),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("main").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.lookup("continue").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("Bool").unwrap()),
            Token::In,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.lookup("choice").unwrap()),
            Token::Colon,
            Token::TypeIdentifier(table.lookup("String").unwrap()),
            Token::In,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("Welcome to the Game of Life.\n").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(
                table
                    .lookup("There are many initial states to choose from. \n")
                    .unwrap(),
            ),
            Token::RParen,
            Token::Semicolon,
            Token::While,
            Token::ObjectIdentifier(table.lookup("prompt2").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Loop,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("continue").unwrap()),
            Token::Assign,
            Token::BoolConst(true),
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("choice").unwrap()),
            Token::Assign,
            Token::ObjectIdentifier(table.lookup("option").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("cells").unwrap()),
            Token::Assign,
            Token::LParen,
            Token::New,
            Token::TypeIdentifier(table.lookup("CellularAutomaton").unwrap()),
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(table.lookup("init").unwrap()),
            Token::LParen,
            Token::ObjectIdentifier(table.lookup("choice").unwrap()),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("cells").unwrap()),
            Token::Dot,
            Token::ObjectIdentifier(table.lookup("print").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::While,
            Token::ObjectIdentifier(table.lookup("continue").unwrap()),
            Token::Loop,
            Token::If,
            Token::ObjectIdentifier(table.lookup("prompt").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("cells").unwrap()),
            Token::Dot,
            Token::ObjectIdentifier(table.lookup("evolve").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.lookup("cells").unwrap()),
            Token::Dot,
            Token::ObjectIdentifier(table.lookup("print").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::RBrace,
            Token::Else,
            Token::ObjectIdentifier(table.lookup("continue").unwrap()),
            Token::Assign,
            Token::BoolConst(false),
            Token::Fi,
            Token::Pool,
            Token::Semicolon,
            Token::RBrace,
            Token::Pool,
            Token::Semicolon,
            Token::SelfValue,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::RParen,
            Token::Semicolon,
            Token::RBrace,
            Token::RBrace,
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
        ];

        assert_eq!(tokens, expected);
    }

    #[test]
    fn hello_world_cl() {
        let src = include_str!("../examples/hello_world.cl");
        let mut s_table = StringTable::new();
        let mut lexer = Token::lexer_with_extras(
            src,
            LexerExtras {
                s_table: &mut s_table,
                file: String::from("test"),
            },
        );
        let tokens: Vec<Token> = lexer.by_ref().map(|t| t.unwrap()).collect();
        let table = &lexer.extras.s_table;

        let expected = vec![
            Token::Class,
            Token::TypeIdentifier(table.lookup("Main").unwrap()),
            Token::Inherits,
            Token::TypeIdentifier(table.lookup("IO").unwrap()),
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("main").unwrap()),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::ObjectIdentifier(table.lookup("out_string").unwrap()),
            Token::LParen,
            Token::StringConstant(table.lookup("Hello, World.\n").unwrap()),
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
        ];

        assert_eq!(tokens, expected);
    }
}

mod fail_lexing {
    use coolc::utils;

    use super::*;

    #[test]
    fn eof_in_string_0() {
        let str = "\"Eof in string";
        let tokens = lex(&str);

        assert_eq!(
            tokens,
            vec![Token::Err(ErrorToken::new(
                ErrorKind::EofInString,
                String::from("EOF in string constant"),
                utils::Span::new(String::from("test"), 0, 14)
            ))]
        )
    }

    #[test]
    fn eof_in_string_1() {
        let str = "\"hello world";

        assert_eq!(
            lex(str),
            vec![Token::Err(ErrorToken::new(
                ErrorKind::EofInString,
                String::from("EOF in string constant"),
                utils::Span::new(String::from("test"), 0, str.len())
            ))]
        );
    }

    #[test]
    fn invalid_char_0() {
        // The character '§' is 2 bytes long in UTF-8
        assert_eq!(
            lex("§"),
            vec![Token::Err(ErrorToken::new(
                ErrorKind::InvalidCharacter,
                String::from("Invalid character: §"),
                utils::Span::new(String::from("test"), 0, 2)
            ))]
        )
    }

    #[test]
    fn invalid_char_1() {
        assert_eq!(
            lex("#"),
            vec![Token::Err(ErrorToken::new(
                ErrorKind::InvalidCharacter,
                String::from("Invalid character: #"),
                utils::Span::new(String::from("test"), 0, 1)
            ))]
        )
    }

    #[test]
    fn unmatched_comment() {
        let str = "*)";

        assert_eq!(
            lex(str),
            vec![Token::Err(ErrorToken::new(
                ErrorKind::UnmatchedCloseComment,
                String::from("Unmatched *)"),
                utils::Span::new(String::from("test"), 0, 2)
            ))]
        )
    }

    #[test]
    fn nested_commments() {
        let str = "(*(*(*(**)*)*)*)*)";

        assert_eq!(
            lex(str),
            vec![Token::Err(ErrorToken::new(
                ErrorKind::UnmatchedCloseComment,
                String::from("Unmatched *)"),
                utils::Span::new(String::from("test"), 16, 18)
            ))]
        )
    }

    #[test]
    fn fail_on_string_constant_too_long() {
        let long_string = format!("\"{}\"", "a".repeat(1026));
        let tokens = lex(&long_string);

        assert_eq!(
            tokens,
            vec![Token::Err(ErrorToken::new(
                ErrorKind::StringConstantTooLong,
                "String constant too long".to_string(),
                utils::Span::new(String::from("test"), 0, long_string.len()),
            ))]
        );
    }

    #[test]
    fn string_contains_null_character() {
        let input = "\"hello\0world\"";

        assert_eq!(
            lex(input),
            vec![Token::Err(ErrorToken::new(
                ErrorKind::StringContainsNullCharacter,
                "String contains null character".to_string(),
                utils::Span::new(String::from("test"), 0, input.len())
            ))]
        );
    }

    #[test]
    fn unterminated_string_recovery() {
        let src = "\"hello world unterminated\nout_string";
        let mut s_table = StringTable::new();
        let mut lex = Token::lexer_with_extras(
            src,
            LexerExtras {
                s_table: &mut s_table,
                file: String::from("test"),
            },
        );

        assert_eq!(
            lex.next(),
            Some(Err(ErrorToken::new(
                ErrorKind::UnterminatedStringConstant,
                String::from("Unterminated string constant"),
                utils::Span::new(String::from("test"), 0, 25)
            )))
        );

        let tok = lex.next().unwrap().unwrap();
        let Token::ObjectIdentifier(id) = tok else {
            panic!("expected ObjectIdentifier")
        };
        assert_eq!(lex.extras.s_table.string_from_id(id).unwrap(), "out_string");
    }

    #[test]
    fn symbols() {
        let src = "+ - = = <- - * ( (*this is a block comment*) ) *) @ #";

        let result = vec![
            Token::Plus,
            Token::Minus,
            Token::Eq,
            Token::Eq,
            Token::Assign,
            Token::Minus,
            Token::Star,
            Token::LParen,
            Token::RParen,
            Token::Err(ErrorToken::new(
                ErrorKind::UnmatchedCloseComment,
                "Unmatched *)".into(),
                utils::Span::new(String::from("test"), 47, 49),
            )),
            Token::At,
            Token::Err(ErrorToken::new(
                ErrorKind::InvalidCharacter,
                "Invalid character: #".to_string(),
                utils::Span::new(String::from("test"), 52, 53),
            )),
        ];

        assert_eq!(lex(src), result);
    }

    #[test]
    fn endline_in_string() {
        let input = "class Main {
            x: String <- \"This is \n a string\";
        };";

        let mut s_table = StringTable::new();

        let expected = vec![
            Token::Class,
            Token::TypeIdentifier(s_table.insert("Main".into())),
            Token::LBrace,
            Token::ObjectIdentifier(s_table.insert("x".into())),
            Token::Colon,
            Token::TypeIdentifier(s_table.insert("String".into())),
            Token::Assign,
            Token::Err(ErrorToken {
                kind: ErrorKind::UnterminatedStringConstant,
                message: "Unterminated string constant".to_string(),
                span: utils::Span::new(String::from("test"), 38, 47),
            }),
            Token::ObjectIdentifier(s_table.insert("a".into())),
            Token::ObjectIdentifier(s_table.insert("string".into())),
            Token::Err(ErrorToken {
                kind: ErrorKind::UnterminatedStringConstant,
                message: "Unterminated string constant".to_string(),
                span: utils::Span::new(String::from("test"), 57, 59),
            }),
            Token::RBrace,
            Token::Semicolon,
        ];

        assert_eq!(lex(input), expected);
    }
}
