use coolc::{
    lexer::{ErrorKind, ErrorToken, LexerExtras, Span, Token},
    s_table::StringTable,
};
use logos::Logos;

fn lex(src: &str) -> Vec<Token> {
    let mut s_table = StringTable::new();
    Token::lexer_with_extras(
        src,
        LexerExtras {
            s_table: &mut s_table,
        },
    )
    .map(|r| r.unwrap_or_else(|e| Token::Err(e)))
    .collect()
}

mod succeeds_lexing {
    use super::*;

    #[test]
    fn test_integer() {
        assert_eq!(lex("123"), vec![Token::Integers(123)]);
    }

    #[test]
    fn nested_comments() {
        assert_eq!(lex("(*(*(*(**)*)*)*)"), vec![]);
    }

    #[test]
    fn hello_world_string() {
        let src = "\"Hello World!\"";
        let mut s_table = StringTable::new();
        let mut lex = Token::lexer_with_extras(
            src,
            LexerExtras {
                s_table: &mut s_table,
            },
        );

        let tok = lex.next().unwrap().unwrap();
        let Token::StringConstant(id) = tok else {
            panic!("expected StringConstant")
        };
        assert_eq!(lex.extras.s_table.get(id).unwrap(), "Hello World!");
    }

    #[test]
    fn cool_cl() {
        let src = include_str!("../examples/cool.cl");
        let mut s_table = StringTable::new();
        let mut lexer = Token::lexer_with_extras(
            src,
            LexerExtras {
                s_table: &mut s_table,
            },
        );
        let tokens: Vec<Token> = lexer.by_ref().map(|t| t.unwrap()).collect();
        let table = &lexer.extras.s_table;
        let expected = vec![
            Token::Class,
            Token::TypeIdentifier(table.map["Main"]),
            Token::Inherits,
            Token::TypeIdentifier(table.map["IO"]),
            Token::LBrace,
            Token::ObjectIdentifier(table.map["main"]),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::LParen,
            Token::New,
            Token::TypeIdentifier(table.map["Object"]),
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(table.map["type_name"]),
            Token::LParen,
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(table.map["substr"]),
            Token::LParen,
            Token::Integers(4),
            Token::Comma,
            Token::Integers(1),
            Token::RParen,
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::LParen,
            Token::IsVoid,
            Token::SelfValue,
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(table.map["type_name"]),
            Token::LParen,
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(table.map["substr"]),
            Token::LParen,
            Token::Integers(1),
            Token::Comma,
            Token::Integers(3),
            Token::RParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::RBrace,
            Token::RBrace,
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
        ];

        assert_eq!(tokens, expected);
    }

    #[test]
    fn primes_cl() {
        let src = include_str!("../examples/primes.cl");
        let mut s_table = StringTable::new();
        let mut lexer = Token::lexer_with_extras(
            src,
            LexerExtras {
                s_table: &mut s_table,
            },
        );
        let tokens: Vec<Token> = lexer.by_ref().map(|t| t.unwrap()).collect();
        let table = &lexer.extras.s_table;

        let expected: Vec<Token> = vec![
            Token::Class,
            Token::TypeIdentifier(table.map["Main"]),
            Token::Inherits,
            Token::TypeIdentifier(table.map["IO"]),
            Token::LBrace,
            Token::ObjectIdentifier(table.map["main"]),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::LBrace,
            Token::Integers(0),
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::Assign,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["2 is trivially prime.\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::Integers(2),
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["testee"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["out"]),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["divisor"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["stop"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::Assign,
            Token::Integers(500),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["m"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Object"]),
            Token::Assign,
            Token::While,
            Token::BoolConst(true),
            Token::Loop,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["testee"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["testee"]),
            Token::Plus,
            Token::Integers(1),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["divisor"]),
            Token::Assign,
            Token::Integers(2),
            Token::Semicolon,
            Token::While,
            Token::If,
            Token::ObjectIdentifier(table.map["testee"]),
            Token::Lt,
            Token::ObjectIdentifier(table.map["divisor"]),
            Token::Star,
            Token::ObjectIdentifier(table.map["divisor"]),
            Token::Then,
            Token::BoolConst(false),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["testee"]),
            Token::Minus,
            Token::ObjectIdentifier(table.map["divisor"]),
            Token::Star,
            Token::LParen,
            Token::ObjectIdentifier(table.map["testee"]),
            Token::Slash,
            Token::ObjectIdentifier(table.map["divisor"]),
            Token::RParen,
            Token::Eq,
            Token::Integers(0),
            Token::Then,
            Token::BoolConst(false),
            Token::Else,
            Token::BoolConst(true),
            Token::Fi,
            Token::Fi,
            Token::Loop,
            Token::ObjectIdentifier(table.map["divisor"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["divisor"]),
            Token::Plus,
            Token::Integers(1),
            Token::Pool,
            Token::Semicolon,
            Token::If,
            Token::ObjectIdentifier(table.map["testee"]),
            Token::Lt,
            Token::ObjectIdentifier(table.map["divisor"]),
            Token::Star,
            Token::ObjectIdentifier(table.map["divisor"]),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["out"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["testee"]),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_int"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["out"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map[" is prime.\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::RBrace,
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Semicolon,
            Token::If,
            Token::ObjectIdentifier(table.map["stop"]),
            Token::Le,
            Token::ObjectIdentifier(table.map["testee"]),
            Token::Then,
            Token::StringConstant(table.map["halt"]),
            Token::Dot,
            Token::ObjectIdentifier(table.map["abort"]),
            Token::LParen,
            Token::RParen,
            Token::Else,
            Token::StringConstant(table.map["continue"]),
            Token::Fi,
            Token::Semicolon,
            Token::RBrace,
            Token::Pool,
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
        ];

        assert_eq!(tokens, expected);
    }

    #[test]
    fn life_cl() {
        let src = include_str!("../examples/life.cl");
        let mut s_table = StringTable::new();
        let mut lexer = Token::lexer_with_extras(
            src,
            LexerExtras {
                s_table: &mut s_table,
            },
        );
        let tokens: Vec<Token> = lexer.by_ref().map(|t| t.unwrap()).collect();
        let table = &lexer.extras.s_table;

        let expected: Vec<Token> = vec![
            Token::Class,
            Token::TypeIdentifier(table.map["Board"]),
            Token::Inherits,
            Token::TypeIdentifier(table.map["IO"]),
            Token::LBrace,
            Token::ObjectIdentifier(table.map["rows"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["board_size"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["size_of_board"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["initial"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::LBrace,
            Token::ObjectIdentifier(table.map["initial"]),
            Token::Dot,
            Token::ObjectIdentifier(table.map["length"]),
            Token::LParen,
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["board_init"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["start"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.map["size"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["size_of_board"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["start"]),
            Token::RParen,
            Token::In,
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(table.map["size"]),
            Token::Eq,
            Token::Integers(15),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["rows"]),
            Token::Assign,
            Token::Integers(3),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::Assign,
            Token::Integers(5),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["board_size"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["size"]),
            Token::Semicolon,
            Token::RBrace,
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["size"]),
            Token::Eq,
            Token::Integers(16),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["rows"]),
            Token::Assign,
            Token::Integers(4),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::Assign,
            Token::Integers(4),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["board_size"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["size"]),
            Token::Semicolon,
            Token::RBrace,
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["size"]),
            Token::Eq,
            Token::Integers(20),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["rows"]),
            Token::Assign,
            Token::Integers(4),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::Assign,
            Token::Integers(5),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["board_size"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["size"]),
            Token::Semicolon,
            Token::RBrace,
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["size"]),
            Token::Eq,
            Token::Integers(21),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["rows"]),
            Token::Assign,
            Token::Integers(3),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::Assign,
            Token::Integers(7),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["board_size"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["size"]),
            Token::Semicolon,
            Token::RBrace,
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["size"]),
            Token::Eq,
            Token::Integers(25),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["rows"]),
            Token::Assign,
            Token::Integers(5),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::Assign,
            Token::Integers(5),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["board_size"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["size"]),
            Token::Semicolon,
            Token::RBrace,
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["size"]),
            Token::Eq,
            Token::Integers(28),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["rows"]),
            Token::Assign,
            Token::Integers(7),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::Assign,
            Token::Integers(4),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["board_size"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["size"]),
            Token::Semicolon,
            Token::RBrace,
            Token::Else,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["rows"]),
            Token::Assign,
            Token::Integers(5),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::Assign,
            Token::Integers(5),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["board_size"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["size"]),
            Token::Semicolon,
            Token::RBrace,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Semicolon,
            Token::SelfValue,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
            Token::Class,
            Token::TypeIdentifier(table.map["CellularAutomaton"]),
            Token::Inherits,
            Token::TypeIdentifier(table.map["Board"]),
            Token::LBrace,
            Token::ObjectIdentifier(table.map["population_map"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["init"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["map"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["population_map"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["map"]),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["board_init"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["map"]),
            Token::RParen,
            Token::Semicolon,
            Token::SelfValue,
            Token::Semicolon,
            Token::RBrace,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["print"]),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.map["i"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::Assign,
            Token::Integers(0),
            Token::In,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["board_size"]),
            Token::In,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::While,
            Token::ObjectIdentifier(table.map["i"]),
            Token::Lt,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Loop,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["population_map"]),
            Token::Dot,
            Token::ObjectIdentifier(table.map["substr"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["i"]),
            Token::Comma,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["i"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["i"]),
            Token::Plus,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::Semicolon,
            Token::RBrace,
            Token::Pool,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::SelfValue,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["num_cells"]),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::LBrace,
            Token::ObjectIdentifier(table.map["population_map"]),
            Token::Dot,
            Token::ObjectIdentifier(table.map["length"]),
            Token::LParen,
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["cell"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(table.map["board_size"]),
            Token::Minus,
            Token::Integers(1),
            Token::Lt,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Then,
            Token::StringConstant(table.map[" "]),
            Token::Else,
            Token::ObjectIdentifier(table.map["population_map"]),
            Token::Dot,
            Token::ObjectIdentifier(table.map["substr"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Comma,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["north"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::LBrace,
            Token::If,
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Minus,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Lt,
            Token::Integers(0),
            Token::Then,
            Token::StringConstant(table.map[" "]),
            Token::Else,
            Token::ObjectIdentifier(table.map["cell"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Minus,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["south"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(table.map["board_size"]),
            Token::Lt,
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Plus,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Then,
            Token::StringConstant(table.map[" "]),
            Token::Else,
            Token::ObjectIdentifier(table.map["cell"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Plus,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["east"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::LBrace,
            Token::If,
            Token::LParen,
            Token::LParen,
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Slash,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Star,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Eq,
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Then,
            Token::StringConstant(table.map[" "]),
            Token::Else,
            Token::ObjectIdentifier(table.map["cell"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["west"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Eq,
            Token::Integers(0),
            Token::Then,
            Token::StringConstant(table.map[" "]),
            Token::Else,
            Token::If,
            Token::LParen,
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Slash,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Star,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Eq,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Then,
            Token::StringConstant(table.map[" "]),
            Token::Else,
            Token::ObjectIdentifier(table.map["cell"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Minus,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["northwest"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::LBrace,
            Token::If,
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Minus,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Lt,
            Token::Integers(0),
            Token::Then,
            Token::StringConstant(table.map[" "]),
            Token::Else,
            Token::If,
            Token::LParen,
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Slash,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Star,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Eq,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Then,
            Token::StringConstant(table.map[" "]),
            Token::Else,
            Token::ObjectIdentifier(table.map["north"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Minus,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["northeast"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::LBrace,
            Token::If,
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Minus,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Lt,
            Token::Integers(0),
            Token::Then,
            Token::StringConstant(table.map[" "]),
            Token::Else,
            Token::If,
            Token::LParen,
            Token::LParen,
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Slash,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Star,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Eq,
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Then,
            Token::StringConstant(table.map[" "]),
            Token::Else,
            Token::ObjectIdentifier(table.map["north"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["southeast"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(table.map["board_size"]),
            Token::Lt,
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Plus,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Then,
            Token::StringConstant(table.map[" "]),
            Token::Else,
            Token::If,
            Token::LParen,
            Token::LParen,
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Slash,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Star,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Eq,
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Then,
            Token::StringConstant(table.map[" "]),
            Token::Else,
            Token::ObjectIdentifier(table.map["south"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["southwest"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(table.map["board_size"]),
            Token::Lt,
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Plus,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Then,
            Token::StringConstant(table.map[" "]),
            Token::Else,
            Token::If,
            Token::LParen,
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Slash,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Star,
            Token::ObjectIdentifier(table.map["columns"]),
            Token::RParen,
            Token::Eq,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Then,
            Token::StringConstant(table.map[" "]),
            Token::Else,
            Token::ObjectIdentifier(table.map["south"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Minus,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["neighbors"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::LBrace,
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(table.map["north"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(table.map["X"]),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(table.map["south"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(table.map["X"]),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(table.map["east"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(table.map["X"]),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(table.map["west"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(table.map["X"]),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(table.map["northeast"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(table.map["X"]),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(table.map["northwest"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(table.map["X"]),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(table.map["southeast"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(table.map["X"]),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(table.map["southwest"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(table.map["X"]),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Semicolon,
            Token::RBrace,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["cell_at_next_evolution"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(table.map["neighbors"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::RParen,
            Token::Eq,
            Token::Integers(3),
            Token::Then,
            Token::StringConstant(table.map["X"]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["neighbors"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::RParen,
            Token::Eq,
            Token::Integers(2),
            Token::Then,
            Token::If,
            Token::ObjectIdentifier(table.map["cell"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(table.map["X"]),
            Token::Then,
            Token::StringConstant(table.map["X"]),
            Token::Else,
            Token::StringConstant(table.map["-"]),
            Token::Fi,
            Token::Else,
            Token::StringConstant(table.map["-"]),
            Token::Fi,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["evolve"]),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::Assign,
            Token::Integers(0),
            Token::In,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["num_cells"]),
            Token::LParen,
            Token::RParen,
            Token::In,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.map["temp"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::In,
            Token::LBrace,
            Token::While,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Lt,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Loop,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["temp"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["temp"]),
            Token::Dot,
            Token::ObjectIdentifier(table.map["concat"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["cell_at_next_evolution"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["position"]),
            Token::RParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["position"]),
            Token::Plus,
            Token::Integers(1),
            Token::Semicolon,
            Token::RBrace,
            Token::Pool,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["population_map"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["temp"]),
            Token::Semicolon,
            Token::SelfValue,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::RParen,
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["option"]),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::LBrace,
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Int"]),
            Token::In,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\nPlease chose a number:\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t1: A cross\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t2: A slash from the upper left to lower right\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t3: A slash from the upper right to lower left\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t4: An X\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t5: A greater than sign \n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t6: A less than sign\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t7: Two greater than signs\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t8: Two less than signs\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t9: A 'V'\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t10: An inverse 'V'\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t11: Numbers 9 and 10 combined\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t12: A full grid\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t13: A 'T'\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t14: A plus '+'\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t15: A 'W'\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t16: An 'M'\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t17: An 'E'\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t18: A '3'\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t19: An 'O'\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t20: An '8'\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\t21: An 'S'\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["Your choice => "]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["in_int"]),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(1),
            Token::Then,
            Token::StringConstant(table.map[" XX  XXXX XXXX  XX  "]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(2),
            Token::Then,
            Token::StringConstant(table.map["    X   X   X   X   X    "]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(3),
            Token::Then,
            Token::StringConstant(table.map["X     X     X     X     X"]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(4),
            Token::Then,
            Token::StringConstant(table.map["X   X X X   X   X X X   X"]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(5),
            Token::Then,
            Token::StringConstant(table.map["X     X     X   X   X    "]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(6),
            Token::Then,
            Token::StringConstant(table.map["    X   X   X     X     X"]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(7),
            Token::Then,
            Token::StringConstant(table.map["X  X  X  XX  X      "]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(8),
            Token::Then,
            Token::StringConstant(table.map[" X  XX  X  X  X     "]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(9),
            Token::Then,
            Token::StringConstant(table.map["X   X X X   X  "]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(10),
            Token::Then,
            Token::StringConstant(table.map["  X   X X X   X"]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(11),
            Token::Then,
            Token::StringConstant(table.map["X X X X X X X X"]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(12),
            Token::Then,
            Token::StringConstant(table.map["XXXXXXXXXXXXXXXXXXXXXXXXX"]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(13),
            Token::Then,
            Token::StringConstant(table.map["XXXXX  X    X    X    X  "]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(14),
            Token::Then,
            Token::StringConstant(table.map["  X    X  XXXXX  X    X  "]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(15),
            Token::Then,
            Token::StringConstant(table.map["X     X X X X   X X  "]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(16),
            Token::Then,
            Token::StringConstant(table.map["  X X   X X X X     X"]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(17),
            Token::Then,
            Token::StringConstant(table.map["XXXXX   X   XXXXX   X   XXXX"]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(18),
            Token::Then,
            Token::StringConstant(table.map["XXX    X   X  X    X   XXXX "]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(19),
            Token::Then,
            Token::StringConstant(table.map[" XX X  XX  X XX "]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(20),
            Token::Then,
            Token::StringConstant(table.map[" XX X  XX  X XX X  XX  X XX "]),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(table.map["num"]),
            Token::Eq,
            Token::Integers(21),
            Token::Then,
            Token::StringConstant(table.map[" XXXX   X    XX    X   XXXX "]),
            Token::Else,
            Token::StringConstant(table.map["                         "]),
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::Semicolon,
            Token::RBrace,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["prompt"]),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.map["Bool"]),
            Token::LBrace,
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.map["ans"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::In,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(
                table.map["Would you like to continue with the next generation? \n"],
            ),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["Please use lowercase y or n for your answer [y]: "]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["ans"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["in_string"]),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::If,
            Token::ObjectIdentifier(table.map["ans"]),
            Token::Eq,
            Token::StringConstant(table.map["n"]),
            Token::Then,
            Token::BoolConst(false),
            Token::Else,
            Token::BoolConst(true),
            Token::Fi,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::Semicolon,
            Token::RBrace,
            Token::RBrace,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["prompt2"]),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(table.map["Bool"]),
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.map["ans"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::In,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["\n\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["Would you like to choose a background pattern? \n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["Please use lowercase y or n for your answer [n]: "]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["ans"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["in_string"]),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::If,
            Token::ObjectIdentifier(table.map["ans"]),
            Token::Eq,
            Token::StringConstant(table.map["y"]),
            Token::Then,
            Token::BoolConst(true),
            Token::Else,
            Token::BoolConst(false),
            Token::Fi,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
            Token::Class,
            Token::TypeIdentifier(table.map["Main"]),
            Token::Inherits,
            Token::TypeIdentifier(table.map["CellularAutomaton"]),
            Token::LBrace,
            Token::ObjectIdentifier(table.map["cells"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["CellularAutomaton"]),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["main"]),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.map["continue"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["Bool"]),
            Token::In,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(table.map["choice"]),
            Token::Colon,
            Token::TypeIdentifier(table.map["String"]),
            Token::In,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["Welcome to the Game of Life.\n"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["There are many initial states to choose from. \n"]),
            Token::RParen,
            Token::Semicolon,
            Token::While,
            Token::ObjectIdentifier(table.map["prompt2"]),
            Token::LParen,
            Token::RParen,
            Token::Loop,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["continue"]),
            Token::Assign,
            Token::BoolConst(true),
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["choice"]),
            Token::Assign,
            Token::ObjectIdentifier(table.map["option"]),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["cells"]),
            Token::Assign,
            Token::LParen,
            Token::New,
            Token::TypeIdentifier(table.map["CellularAutomaton"]),
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(table.map["init"]),
            Token::LParen,
            Token::ObjectIdentifier(table.map["choice"]),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["cells"]),
            Token::Dot,
            Token::ObjectIdentifier(table.map["print"]),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::While,
            Token::ObjectIdentifier(table.map["continue"]),
            Token::Loop,
            Token::If,
            Token::ObjectIdentifier(table.map["prompt"]),
            Token::LParen,
            Token::RParen,
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["cells"]),
            Token::Dot,
            Token::ObjectIdentifier(table.map["evolve"]),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(table.map["cells"]),
            Token::Dot,
            Token::ObjectIdentifier(table.map["print"]),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::RBrace,
            Token::Else,
            Token::ObjectIdentifier(table.map["continue"]),
            Token::Assign,
            Token::BoolConst(false),
            Token::Fi,
            Token::Pool,
            Token::Semicolon,
            Token::RBrace,
            Token::Pool,
            Token::Semicolon,
            Token::SelfValue,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::RParen,
            Token::Semicolon,
            Token::RBrace,
            Token::RBrace,
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
        ];

        assert_eq!(tokens, expected);
    }

    #[test]
    fn hello_world_cl() {
        let src = include_str!("../examples/hello_world.cl");
        let mut s_table = StringTable::new();
        let mut lexer = Token::lexer_with_extras(
            src,
            LexerExtras {
                s_table: &mut s_table,
            },
        );
        let tokens: Vec<Token> = lexer.by_ref().map(|t| t.unwrap()).collect();
        let table = &lexer.extras.s_table;

        let expected = vec![
            Token::Class,
            Token::TypeIdentifier(table.map["Main"]),
            Token::Inherits,
            Token::TypeIdentifier(table.map["IO"]),
            Token::LBrace,
            Token::ObjectIdentifier(table.map["main"]),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::ObjectIdentifier(table.map["out_string"]),
            Token::LParen,
            Token::StringConstant(table.map["Hello, World.\n"]),
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
        ];

        assert_eq!(tokens, expected);
    }
}

mod fail_lexing {
    use super::*;

    #[test]
    fn eof_in_string_0() {
        let str = "\"Eof in string";
        let tokens = lex(&str);

        assert_eq!(
            tokens,
            vec![Token::Err(ErrorToken::new(
                ErrorKind::EofInString,
                Some(String::from("EOF in string constant")),
                Span::new(0, 14)
            ))]
        )
    }

    #[test]
    fn eof_in_string_1() {
        let str = "\"hello world";

        assert_eq!(
            lex(str),
            vec![Token::Err(ErrorToken::new(
                ErrorKind::EofInString,
                Some(String::from("EOF in string constant")),
                Span::new(0, str.len())
            ))]
        );
    }

    #[test]
    fn invalid_char_0() {
        // The character '§' is 2 bytes long in UTF-8
        assert_eq!(
            lex("§"),
            vec![Token::Err(ErrorToken::new(
                ErrorKind::InvalidCharacter,
                Some(String::from("§")),
                Span::new(0, 2)
            ))]
        )
    }

    #[test]
    fn invalid_char_1() {
        assert_eq!(
            lex("#"),
            vec![Token::Err(ErrorToken::new(
                ErrorKind::InvalidCharacter,
                Some(String::from("#")),
                Span::new(0, 1)
            ))]
        )
    }

    #[test]
    fn unmatched_comment() {
        let str = "*)";

        assert_eq!(
            lex(str),
            vec![Token::Err(ErrorToken::new(
                ErrorKind::UnmatchedCloseComment,
                Some(String::from("Unmatched *)")),
                Span::new(0, 2)
            ))]
        )
    }

    #[test]
    fn nested_commments() {
        let str = "(*(*(*(**)*)*)*)*)";

        assert_eq!(
            lex(str),
            vec![Token::Err(ErrorToken::new(
                ErrorKind::UnmatchedCloseComment,
                Some(String::from("Unmatched *)")),
                Span::new(16, 18)
            ))]
        )
    }

    #[test]
    fn fail_on_string_constant_too_long() {
        let long_string = format!("\"{}\"", "a".repeat(1026));
        let tokens = lex(&long_string);

        assert_eq!(
            tokens,
            vec![Token::Err(ErrorToken::new(
                ErrorKind::StringConstantTooLong,
                Some("String constant too long".to_string()),
                Span::new(0, long_string.len()),
            ))]
        );
    }

    #[test]
    fn string_contains_null_character() {
        let input = "\"hello\0world\"";

        assert_eq!(
            lex(input),
            vec![Token::Err(ErrorToken::new(
                ErrorKind::StringContainsNullCharacter,
                Some("String contains null character".to_string()),
                Span::new(0, input.len())
            ))]
        );
    }

    #[test]
    fn unterminated_string_recovery() {
        let src = "\"hello world unterminated\nout_string";
        let mut s_table = StringTable::new();
        let mut lex = Token::lexer_with_extras(
            src,
            LexerExtras {
                s_table: &mut s_table,
            },
        );

        assert_eq!(
            lex.next(),
            Some(Err(ErrorToken::new(
                ErrorKind::UnterminatedStringConstant,
                Some(String::from("Unterminated string constant")),
                Span::new(0, 25)
            )))
        );

        let tok = lex.next().unwrap().unwrap();
        let Token::ObjectIdentifier(id) = tok else {
            panic!("expected ObjectIdentifier")
        };
        assert_eq!(lex.extras.s_table.get(id).unwrap(), "out_string");
    }

    #[test]
    fn symbols() {
        let src = "+ - = = <- - * ( (*this is a block comment*) ) *) @ #";

        let result = vec![
            Token::Plus,
            Token::Minus,
            Token::Eq,
            Token::Eq,
            Token::Assign,
            Token::Minus,
            Token::Star,
            Token::LParen,
            Token::RParen,
            Token::Err(ErrorToken::new(
                ErrorKind::UnmatchedCloseComment,
                Some("Unmatched *)".into()),
                Span::new(47, 49),
            )),
            Token::At,
            Token::Err(ErrorToken::new(
                ErrorKind::InvalidCharacter,
                Some("#".into()),
                Span::new(52, 53),
            )),
        ];

        assert_eq!(lex(src), result);
    }
}
