use logos::{FilterResult, Lexer, Logos, Skip};

const MAX_STR_CONST_LEN: usize = 1024;

#[derive(Default, Debug, Clone, PartialEq)]
enum ErrorKind {
    InvalidCharacter,

    // String constant lexing errors
    UnterminatedStringConstant,
    StringContainsNullCharacter,
    StringConstantTooLong,
    EofInString,

    // Comment lexing errors
    EofInComment,
    UnmatchedCloseComment,

    #[default]
    Other,
}

#[derive(Default, Debug, PartialEq, Clone)]
struct ErrorToken {
    kind: ErrorKind,
    message: Option<String>,
}

impl ErrorToken {
    fn new(kind: ErrorKind, message: Option<String>) -> Self {
        Self { kind, message }
    }
}

#[derive(Logos, Debug, PartialEq)]
#[logos(subpattern alpha = r"[a-zA-Z]")]
#[logos(subpattern digit = r"[0-9]")]
#[logos(subpattern alphanum = r"(?&alpha)|(?&digit)|_")]
#[logos(extras = (usize, usize))]
#[logos(skip(r"\n", newline_callback))]
#[logos(skip(r"[ \v\r\t\f]+"))]
#[logos(error = ErrorToken)]
enum Token {
    #[token(".")]
    Dot,

    #[token("@")]
    At,

    #[token("~")]
    Tilde,

    #[token("/")]
    Slash,

    #[token("+")]
    Plus,

    #[token("-")]
    Minus,

    #[token("=>")]
    FatArrow,

    #[token("<")]
    Lt,

    #[token("<=")]
    Le,

    #[token(">")]
    Gt,

    #[token(">=")]
    Ge,

    #[token("*")]
    Star,

    #[token("<-")]
    Assign,

    #[token(";")]
    Semicolon,

    #[token(",")]
    Comma,

    #[token(":")]
    Colon,

    #[token("{")]
    LBrace,

    #[token("}")]
    RBrace,

    #[token("(")]
    LParen,

    #[token(")")]
    RParen,

    #[token("=")]
    Eq,

    #[token("self")]
    SelfValue,

    #[token("SELF_TYPE")]
    SelfType,

    #[regex("(?i)class")]
    Class,

    #[regex("(?i)else")]
    Else,

    #[regex("(?i)fi")]
    Fi,

    #[regex("(?i)if")]
    If,

    #[regex("(?i)in")]
    In,

    #[regex("(?i)inherits")]
    Inherits,

    #[regex("(?i)isvoid")]
    IsVoid,

    #[regex("(?i)let")]
    Let,

    #[regex("(?i)loop")]
    Loop,

    #[regex("(?i)pool")]
    Pool,

    #[regex("(?i)then")]
    Then,

    #[regex("(?i)while")]
    While,

    #[regex("(?i)case")]
    Case,

    #[regex("(?i)esac")]
    Esac,

    #[regex("(?i)new")]
    New,

    #[regex("(?i)of")]
    Of,

    #[regex("(?i)not")]
    Not,

    #[regex("t(?i:rue)", |_| true)]
    #[regex("f(?i:alse)", |_| false)]
    BoolConst(bool),

    #[regex("(?&digit)+", |lex| lex.slice().parse().ok())]
    Integers(i64),

    #[regex("[A-Z](?&alphanum)*", |lex| lex.slice().to_string())]
    TypeIdentifier(String),

    #[regex("[a-z](?&alphanum)*", |lex| lex.slice().to_string())]
    ObjectIdentifier(String),

    #[token("\"", string_callback)]
    StringConstant(String),

    #[regex(r"--[^\n]*", logos::skip, allow_greedy = true)]
    #[token("(*", block_comment_callback)]
    BlockComment,

    #[token("*)", unmatched_close_comment_callback)]
    UnmatchedCloseComment,

    #[regex(".", invalid_character_callback, priority = 1)]
    Err(ErrorToken),
}

fn newline_callback(lex: &mut Lexer<Token>) -> Skip {
    lex.extras.0 += 1;
    lex.extras.1 = lex.span().end;
    Skip
}

fn block_comment_callback(lex: &mut Lexer<Token>) -> FilterResult<(), ErrorToken> {
    let mut depth = 1usize;
    let mut chars = lex.remainder().char_indices().peekable();

    while let Some((i, c)) = chars.next() {
        match c {
            '(' if chars.peek().map(|&(_, c)| c) == Some('*') => {
                chars.next();
                depth += 1;
            }
            '*' if chars.peek().map(|&(_, c)| c) == Some(')') => {
                chars.next();
                depth -= 1;
                if depth == 0 {
                    lex.bump(i + 2);
                    return FilterResult::Skip;
                }
            }
            _ => {}
        }
    }

    lex.bump(lex.remainder().len());
    FilterResult::Error(ErrorToken::new(
        ErrorKind::EofInComment,
        Some(String::from("EOF in comment")),
    ))
}

fn string_callback(lex: &mut Lexer<Token>) -> Result<String, ErrorToken> {
    let mut result = String::new();
    let mut chars = lex.remainder().chars().peekable();
    let mut consumed_bytes = 0;

    while let Some(c) = chars.next() {
        consumed_bytes += c.len_utf8();

        match c {
            '\0' => {
                while let Some(&next_c) = chars.peek() {
                    if next_c == '"' || next_c == '\n' {
                        if next_c == '"' {
                            chars.next();
                            consumed_bytes += next_c.len_utf8();
                        }
                        break;
                    }
                    chars.next();
                    consumed_bytes += next_c.len_utf8();
                }
                lex.bump(consumed_bytes);
                return Err(ErrorToken::new(
                    ErrorKind::StringContainsNullCharacter,
                    Some(String::from("String contains null character")),
                ));
            }
            '\n' => {
                lex.bump(consumed_bytes - c.len_utf8());
                return Err(ErrorToken::new(
                    ErrorKind::UnterminatedStringConstant,
                    Some(String::from("Unterminated string constant")),
                ));
            }
            '"' => {
                lex.bump(consumed_bytes);
                return Ok(result);
            }
            '\\' => {
                if let Some(next_c) = chars.next() {
                    consumed_bytes += next_c.len_utf8();
                    match next_c {
                        'n' => result.push('\n'),
                        't' => result.push('\t'),
                        'b' => result.push('\x08'),
                        'f' => result.push('\x0C'),
                        '\\' => result.push('\\'),
                        '"' => result.push('"'),
                        '0' => {
                            while let Some(&next_c) = chars.peek() {
                                if next_c == '"' || next_c == '\n' {
                                    if next_c == '"' {
                                        chars.next();
                                        consumed_bytes += next_c.len_utf8();
                                    }
                                    break;
                                }

                                chars.next();
                                consumed_bytes += next_c.len_utf8();
                            }

                            lex.bump(consumed_bytes);

                            return Err(ErrorToken::new(
                                ErrorKind::StringContainsNullCharacter,
                                Some(String::from("String contains null character")),
                            ));
                        }
                        _ => result.push(next_c),
                    }
                } else {
                    lex.bump(consumed_bytes);
                    return Err(ErrorToken::new(
                        ErrorKind::EofInString,
                        Some(String::from("EOF in string constant")),
                    ));
                }
            }
            _ => {
                result.push(c);
            }
        }

        if result.len() > MAX_STR_CONST_LEN {
            while let Some(&next_c) = chars.peek() {
                if next_c == '"' || next_c == '\n' {
                    if next_c == '"' {
                        chars.next();
                        consumed_bytes += next_c.len_utf8();
                    }
                    break;
                }
                chars.next();
                consumed_bytes += next_c.len_utf8();
            }
            lex.bump(consumed_bytes);
            return Err(ErrorToken::new(
                ErrorKind::StringConstantTooLong,
                Some(String::from("String constant too long")),
            ));
        }
    }

    lex.bump(consumed_bytes);
    Err(ErrorToken::new(
        ErrorKind::EofInString,
        Some(String::from("EOF in string constant")),
    ))
}

fn invalid_character_callback(lex: &mut Lexer<Token>) -> ErrorToken {
    ErrorToken::new(ErrorKind::InvalidCharacter, Some(lex.slice().to_string()))
}

fn unmatched_close_comment_callback(_lex: &mut Lexer<Token>) -> Result<logos::Skip, ErrorToken> {
    Err(ErrorToken::new(
        ErrorKind::UnmatchedCloseComment,
        Some(String::from("Unmatched *)")),
    ))
}

#[cfg(test)]
mod test {
    use super::*;
    use logos::Logos;

    fn lex(src: &str) -> Vec<Token> {
        Token::lexer(src)
            .map(|r| r.unwrap_or_else(|e| Token::Err(e)))
            .collect()
    }

    #[test]
    fn test_integer() {
        assert_eq!(lex("123"), vec![Token::Integers(123)]);
    }

    #[test]
    fn hello_world_string() {
        assert_eq!(
            lex("\"Hello World!\""),
            vec![Token::StringConstant(String::from("Hello World!"))]
        );
    }

    #[test]
    fn string_constant_too_long() {
        let long_string = format!("\"{}\"", "a".repeat(1026));
        assert_eq!(
            lex(&long_string),
            vec![Token::Err(ErrorToken::new(
                ErrorKind::StringConstantTooLong,
                Some(String::from("String constant too long"))
            ))]
        );
    }

    #[test]
    fn string_contains_null_character() {
        assert_eq!(
            lex("\"hello\0world\""),
            vec![Token::Err(ErrorToken::new(
                ErrorKind::StringContainsNullCharacter,
                Some(String::from("String contains null character"))
            ))]
        );
    }

    #[test]
    fn eof_in_string() {
        assert_eq!(
            lex("\"hello world"),
            vec![Token::Err(ErrorToken::new(
                ErrorKind::EofInString,
                Some(String::from("EOF in string constant"))
            ))]
        );
    }

    #[test]
    fn unterminated_string_recovery() {
        let src = "\"hello #world unterminated\nout_string";

        assert_eq!(
            lex(src),
            vec![
                Token::Err(ErrorToken::new(
                    ErrorKind::UnterminatedStringConstant,
                    Some(String::from("Unterminated string constant"))
                )),
                Token::ObjectIdentifier("out_string".to_string()),
            ]
        );
    }

    #[test]
    fn symbols() {
        let src = "+ - = = <- - * ( (*this is a block comment*) ) *) @ #";
        let result = vec![
            Token::Plus,
            Token::Minus,
            Token::Eq,
            Token::Eq,
            Token::Assign,
            Token::Minus,
            Token::Star,
            Token::LParen,
            Token::RParen,
            Token::Err(ErrorToken::new(
                ErrorKind::UnmatchedCloseComment,
                Some("Unmatched *)".into()),
            )),
            Token::At,
            Token::Err(ErrorToken::new(
                ErrorKind::InvalidCharacter,
                Some("#".into()),
            )),
        ];
        assert_eq!(lex(src), result);
    }

    #[test]
    fn cool_cl() {
        let src = include_str!("../examples/cool.cl");
        let result = vec![
            Token::Class,
            Token::TypeIdentifier(String::from("Main")),
            Token::Inherits,
            Token::TypeIdentifier(String::from("IO")),
            Token::LBrace,
            Token::ObjectIdentifier(String::from("main")),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::LParen,
            Token::New,
            Token::TypeIdentifier(String::from("Object")),
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(String::from("type_name")),
            Token::LParen,
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(String::from("substr")),
            Token::LParen,
            Token::Integers(4),
            Token::Comma,
            Token::Integers(1),
            Token::RParen,
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::LParen,
            Token::IsVoid,
            Token::SelfValue,
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(String::from("type_name")),
            Token::LParen,
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(String::from("substr")),
            Token::LParen,
            Token::Integers(1),
            Token::Comma,
            Token::Integers(3),
            Token::RParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\n")),
            Token::RParen,
            Token::Semicolon,
            Token::RBrace,
            Token::RBrace,
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
        ];
        assert_eq!(lex(src), result);
    }

    #[test]
    fn io_cl() {
        let src = include_str!("../examples/io.cl");
        let result = vec![
            // class A {
            Token::Class,
            Token::TypeIdentifier(String::from("A")),
            Token::LBrace,
            // io : IO <- new IO;
            Token::ObjectIdentifier(String::from("io")),
            Token::Colon,
            Token::TypeIdentifier(String::from("IO")),
            Token::Assign,
            Token::New,
            Token::TypeIdentifier(String::from("IO")),
            Token::Semicolon,
            // out_a() : Object { io.out_string("A: Hello world\n") };
            Token::ObjectIdentifier(String::from("out_a")),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("Object")),
            Token::LBrace,
            Token::ObjectIdentifier(String::from("io")),
            Token::Dot,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("A: Hello world\n")),
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            // };
            Token::RBrace,
            Token::Semicolon,
            // class B inherits A {
            Token::Class,
            Token::TypeIdentifier(String::from("B")),
            Token::Inherits,
            Token::TypeIdentifier(String::from("A")),
            Token::LBrace,
            // out_b() : Object { io.out_string("B: Hello world\n") };
            Token::ObjectIdentifier(String::from("out_b")),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("Object")),
            Token::LBrace,
            Token::ObjectIdentifier(String::from("io")),
            Token::Dot,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("B: Hello world\n")),
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            // };
            Token::RBrace,
            Token::Semicolon,
            // class C inherits IO {
            Token::Class,
            Token::TypeIdentifier(String::from("C")),
            Token::Inherits,
            Token::TypeIdentifier(String::from("IO")),
            Token::LBrace,
            // out_c() : Object { out_string("C: Hello world\n") };
            Token::ObjectIdentifier(String::from("out_c")),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("Object")),
            Token::LBrace,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("C: Hello world\n")),
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            // };
            Token::RBrace,
            Token::Semicolon,
            // class D inherits C {
            Token::Class,
            Token::TypeIdentifier(String::from("D")),
            Token::Inherits,
            Token::TypeIdentifier(String::from("C")),
            Token::LBrace,
            // out_d() : Object { out_string("D: Hello world\n") };
            Token::ObjectIdentifier(String::from("out_d")),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("Object")),
            Token::LBrace,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("D: Hello world\n")),
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            // };
            Token::RBrace,
            Token::Semicolon,
            // class Main inherits IO {
            Token::Class,
            Token::TypeIdentifier(String::from("Main")),
            Token::Inherits,
            Token::TypeIdentifier(String::from("IO")),
            Token::LBrace,
            // main() : Object {
            Token::ObjectIdentifier(String::from("main")),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("Object")),
            Token::LBrace,
            // {
            Token::LBrace,
            // (new A).out_a();
            Token::LParen,
            Token::New,
            Token::TypeIdentifier(String::from("A")),
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(String::from("out_a")),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            // (new B).out_b();
            Token::LParen,
            Token::New,
            Token::TypeIdentifier(String::from("B")),
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(String::from("out_b")),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            // (new C).out_c();
            Token::LParen,
            Token::New,
            Token::TypeIdentifier(String::from("C")),
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(String::from("out_c")),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            // (new D).out_d();
            Token::LParen,
            Token::New,
            Token::TypeIdentifier(String::from("D")),
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(String::from("out_d")),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            // out_string("Done.\n");
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("Done.\n")),
            Token::RParen,
            Token::Semicolon,
            // }
            Token::RBrace,
            // };
            Token::RBrace,
            Token::Semicolon,
            // };
            Token::RBrace,
            Token::Semicolon,
        ];
        assert_eq!(lex(src), result);
    }

    #[test]
    fn primes_cl() {
        let src = include_str!("../examples/primes.cl");
        let result = vec![
            // class Main inherits IO {
            Token::Class,
            Token::TypeIdentifier(String::from("Main")),
            Token::Inherits,
            Token::TypeIdentifier(String::from("IO")),
            Token::LBrace,
            // main() : Int {
            Token::ObjectIdentifier(String::from("main")),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::LBrace,
            Token::Integers(0),
            Token::RBrace,
            Token::Semicolon,
            // out : Int <- { out_string("2 is trivially prime.\n"); 2; };
            Token::ObjectIdentifier(String::from("out")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::Assign,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("2 is trivially prime.\n")),
            Token::RParen,
            Token::Semicolon,
            Token::Integers(2),
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
            // testee : Int <- out;
            Token::ObjectIdentifier(String::from("testee")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("out")),
            Token::Semicolon,
            // divisor : Int;
            Token::ObjectIdentifier(String::from("divisor")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::Semicolon,
            // stop : Int <- 500;
            Token::ObjectIdentifier(String::from("stop")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::Assign,
            Token::Integers(500),
            Token::Semicolon,
            // m : Object <- while true loop { ... } pool;
            Token::ObjectIdentifier(String::from("m")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Object")),
            Token::Assign,
            Token::While,
            Token::BoolConst(true),
            Token::Loop,
            Token::LBrace,
            // testee <- testee + 1;
            Token::ObjectIdentifier(String::from("testee")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("testee")),
            Token::Plus,
            Token::Integers(1),
            Token::Semicolon,
            // divisor <- 2;
            Token::ObjectIdentifier(String::from("divisor")),
            Token::Assign,
            Token::Integers(2),
            Token::Semicolon,
            // while if testee < divisor * divisor then false else if testee - divisor*(testee/divisor) = 0 then false else true fi fi loop
            Token::While,
            Token::If,
            Token::ObjectIdentifier(String::from("testee")),
            Token::Lt,
            Token::ObjectIdentifier(String::from("divisor")),
            Token::Star,
            Token::ObjectIdentifier(String::from("divisor")),
            Token::Then,
            Token::BoolConst(false),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("testee")),
            Token::Minus,
            Token::ObjectIdentifier(String::from("divisor")),
            Token::Star,
            Token::LParen,
            Token::ObjectIdentifier(String::from("testee")),
            Token::Slash,
            Token::ObjectIdentifier(String::from("divisor")),
            Token::RParen,
            Token::Eq,
            Token::Integers(0),
            Token::Then,
            Token::BoolConst(false),
            Token::Else,
            Token::BoolConst(true),
            Token::Fi,
            Token::Fi,
            Token::Loop,
            // divisor <- divisor + 1
            Token::ObjectIdentifier(String::from("divisor")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("divisor")),
            Token::Plus,
            Token::Integers(1),
            Token::Pool,
            Token::Semicolon,
            // if testee < divisor * divisor
            Token::If,
            Token::ObjectIdentifier(String::from("testee")),
            Token::Lt,
            Token::ObjectIdentifier(String::from("divisor")),
            Token::Star,
            Token::ObjectIdentifier(String::from("divisor")),
            Token::Then,
            Token::LBrace,
            // out <- testee;
            Token::ObjectIdentifier(String::from("out")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("testee")),
            Token::Semicolon,
            // out_int(out);
            Token::ObjectIdentifier(String::from("out_int")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("out")),
            Token::RParen,
            Token::Semicolon,
            // out_string(" is prime.\n");
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from(" is prime.\n")),
            Token::RParen,
            Token::Semicolon,
            Token::RBrace,
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Semicolon,
            // if stop <= testee then "halt".abort() else "continue" fi;
            Token::If,
            Token::ObjectIdentifier(String::from("stop")),
            Token::Le,
            Token::ObjectIdentifier(String::from("testee")),
            Token::Then,
            Token::StringConstant(String::from("halt")),
            Token::Dot,
            Token::ObjectIdentifier(String::from("abort")),
            Token::LParen,
            Token::RParen,
            Token::Else,
            Token::StringConstant(String::from("continue")),
            Token::Fi,
            Token::Semicolon,
            Token::RBrace,
            Token::Pool,
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
        ];

        assert_eq!(lex(src), result);
    }

    #[test]
    fn life_cl() {
        let src = include_str!("../examples/life.cl");
        let result = vec![
            // class Board inherits IO {
            Token::Class,
            Token::TypeIdentifier(String::from("Board")),
            Token::Inherits,
            Token::TypeIdentifier(String::from("IO")),
            Token::LBrace,
            // rows : Int;
            Token::ObjectIdentifier(String::from("rows")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::Semicolon,
            // columns : Int;
            Token::ObjectIdentifier(String::from("columns")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::Semicolon,
            // board_size : Int;
            Token::ObjectIdentifier(String::from("board_size")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::Semicolon,
            // size_of_board(initial : String) : Int { initial.length() };
            Token::ObjectIdentifier(String::from("size_of_board")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("initial")),
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::LBrace,
            Token::ObjectIdentifier(String::from("initial")),
            Token::Dot,
            Token::ObjectIdentifier(String::from("length")),
            Token::LParen,
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            // board_init(start : String) : SELF_TYPE {
            Token::ObjectIdentifier(String::from("board_init")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("start")),
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(String::from("size")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("size_of_board")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("start")),
            Token::RParen,
            Token::In,
            Token::LBrace,
            // if size = 15 then
            Token::If,
            Token::ObjectIdentifier(String::from("size")),
            Token::Eq,
            Token::Integers(15),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("rows")),
            Token::Assign,
            Token::Integers(3),
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("columns")),
            Token::Assign,
            Token::Integers(5),
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("board_size")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("size")),
            Token::Semicolon,
            Token::RBrace,
            // else if size = 16
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("size")),
            Token::Eq,
            Token::Integers(16),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("rows")),
            Token::Assign,
            Token::Integers(4),
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("columns")),
            Token::Assign,
            Token::Integers(4),
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("board_size")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("size")),
            Token::Semicolon,
            Token::RBrace,
            // else if size = 20
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("size")),
            Token::Eq,
            Token::Integers(20),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("rows")),
            Token::Assign,
            Token::Integers(4),
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("columns")),
            Token::Assign,
            Token::Integers(5),
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("board_size")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("size")),
            Token::Semicolon,
            Token::RBrace,
            // else if size = 21
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("size")),
            Token::Eq,
            Token::Integers(21),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("rows")),
            Token::Assign,
            Token::Integers(3),
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("columns")),
            Token::Assign,
            Token::Integers(7),
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("board_size")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("size")),
            Token::Semicolon,
            Token::RBrace,
            // else if size = 25
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("size")),
            Token::Eq,
            Token::Integers(25),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("rows")),
            Token::Assign,
            Token::Integers(5),
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("columns")),
            Token::Assign,
            Token::Integers(5),
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("board_size")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("size")),
            Token::Semicolon,
            Token::RBrace,
            // else if size = 28
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("size")),
            Token::Eq,
            Token::Integers(28),
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("rows")),
            Token::Assign,
            Token::Integers(7),
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("columns")),
            Token::Assign,
            Token::Integers(4),
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("board_size")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("size")),
            Token::Semicolon,
            Token::RBrace,
            // else
            Token::Else,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("rows")),
            Token::Assign,
            Token::Integers(5),
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("columns")),
            Token::Assign,
            Token::Integers(5),
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("board_size")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("size")),
            Token::Semicolon,
            Token::RBrace,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Semicolon,
            Token::SelfValue,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
            // class CellularAutomaton inherits Board {
            Token::Class,
            Token::TypeIdentifier(String::from("CellularAutomaton")),
            Token::Inherits,
            Token::TypeIdentifier(String::from("Board")),
            Token::LBrace,
            // population_map : String;
            Token::ObjectIdentifier(String::from("population_map")),
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::Semicolon,
            // init(map : String) : SELF_TYPE {
            Token::ObjectIdentifier(String::from("init")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("map")),
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("population_map")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("map")),
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("board_init")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("map")),
            Token::RParen,
            Token::Semicolon,
            Token::SelfValue,
            Token::Semicolon,
            Token::RBrace,
            Token::RBrace,
            Token::Semicolon,
            // print() : SELF_TYPE {
            Token::ObjectIdentifier(String::from("print")),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(String::from("i")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::Assign,
            Token::Integers(0),
            Token::In,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(String::from("num")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("board_size")),
            Token::In,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\n")),
            Token::RParen,
            Token::Semicolon,
            Token::While,
            Token::ObjectIdentifier(String::from("i")),
            Token::Lt,
            Token::ObjectIdentifier(String::from("num")),
            Token::Loop,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("population_map")),
            Token::Dot,
            Token::ObjectIdentifier(String::from("substr")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("i")),
            Token::Comma,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("i")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("i")),
            Token::Plus,
            Token::ObjectIdentifier(String::from("columns")),
            Token::Semicolon,
            Token::RBrace,
            Token::Pool,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\n")),
            Token::RParen,
            Token::Semicolon,
            Token::SelfValue,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            // num_cells() : Int {
            Token::ObjectIdentifier(String::from("num_cells")),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::LBrace,
            Token::ObjectIdentifier(String::from("population_map")),
            Token::Dot,
            Token::ObjectIdentifier(String::from("length")),
            Token::LParen,
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            // cell(position : Int) : String {
            Token::ObjectIdentifier(String::from("cell")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(String::from("board_size")),
            Token::Minus,
            Token::Integers(1),
            Token::Lt,
            Token::ObjectIdentifier(String::from("position")),
            Token::Then,
            Token::StringConstant(String::from(" ")),
            Token::Else,
            Token::ObjectIdentifier(String::from("population_map")),
            Token::Dot,
            Token::ObjectIdentifier(String::from("substr")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Comma,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            // north(position : Int): String {
            Token::ObjectIdentifier(String::from("north")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::LBrace,
            Token::If,
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Minus,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Lt,
            Token::Integers(0),
            Token::Then,
            Token::StringConstant(String::from(" ")),
            Token::Else,
            Token::ObjectIdentifier(String::from("cell")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Minus,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            // south(position : Int): String {
            Token::ObjectIdentifier(String::from("south")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(String::from("board_size")),
            Token::Lt,
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Plus,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Then,
            Token::StringConstant(String::from(" ")),
            Token::Else,
            Token::ObjectIdentifier(String::from("cell")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Plus,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            // east(position : Int): String {
            Token::ObjectIdentifier(String::from("east")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::LBrace,
            Token::If,
            Token::LParen,
            Token::LParen,
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Slash,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Star,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Eq,
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Then,
            Token::StringConstant(String::from(" ")),
            Token::Else,
            Token::ObjectIdentifier(String::from("cell")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            // west(position : Int): String {
            Token::ObjectIdentifier(String::from("west")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(String::from("position")),
            Token::Eq,
            Token::Integers(0),
            Token::Then,
            Token::StringConstant(String::from(" ")),
            Token::Else,
            Token::If,
            Token::LParen,
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Slash,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Star,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Eq,
            Token::ObjectIdentifier(String::from("position")),
            Token::Then,
            Token::StringConstant(String::from(" ")),
            Token::Else,
            Token::ObjectIdentifier(String::from("cell")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Minus,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            // northwest(position : Int): String {
            Token::ObjectIdentifier(String::from("northwest")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::LBrace,
            Token::If,
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Minus,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Lt,
            Token::Integers(0),
            Token::Then,
            Token::StringConstant(String::from(" ")),
            Token::Else,
            Token::If,
            Token::LParen,
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Slash,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Star,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Eq,
            Token::ObjectIdentifier(String::from("position")),
            Token::Then,
            Token::StringConstant(String::from(" ")),
            Token::Else,
            Token::ObjectIdentifier(String::from("north")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Minus,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            // northeast(position : Int): String {
            Token::ObjectIdentifier(String::from("northeast")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::LBrace,
            Token::If,
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Minus,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Lt,
            Token::Integers(0),
            Token::Then,
            Token::StringConstant(String::from(" ")),
            Token::Else,
            Token::If,
            Token::LParen,
            Token::LParen,
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Slash,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Star,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Eq,
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Then,
            Token::StringConstant(String::from(" ")),
            Token::Else,
            Token::ObjectIdentifier(String::from("north")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            // southeast(position : Int): String {
            Token::ObjectIdentifier(String::from("southeast")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(String::from("board_size")),
            Token::Lt,
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Plus,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Then,
            Token::StringConstant(String::from(" ")),
            Token::Else,
            Token::If,
            Token::LParen,
            Token::LParen,
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Slash,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Star,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Eq,
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Then,
            Token::StringConstant(String::from(" ")),
            Token::Else,
            Token::ObjectIdentifier(String::from("south")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Plus,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            // southwest(position : Int): String {
            Token::ObjectIdentifier(String::from("southwest")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(String::from("board_size")),
            Token::Lt,
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Plus,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Then,
            Token::StringConstant(String::from(" ")),
            Token::Else,
            Token::If,
            Token::LParen,
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Slash,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Star,
            Token::ObjectIdentifier(String::from("columns")),
            Token::RParen,
            Token::Eq,
            Token::ObjectIdentifier(String::from("position")),
            Token::Then,
            Token::StringConstant(String::from(" ")),
            Token::Else,
            Token::ObjectIdentifier(String::from("south")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Minus,
            Token::Integers(1),
            Token::RParen,
            Token::Fi,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            // neighbors(position: Int): Int {
            Token::ObjectIdentifier(String::from("neighbors")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::LBrace,
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(String::from("north")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(String::from("X")),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(String::from("south")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(String::from("X")),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(String::from("east")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(String::from("X")),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(String::from("west")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(String::from("X")),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(String::from("northeast")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(String::from("X")),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(String::from("northwest")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(String::from("X")),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(String::from("southeast")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(String::from("X")),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Plus,
            Token::If,
            Token::ObjectIdentifier(String::from("southwest")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(String::from("X")),
            Token::Then,
            Token::Integers(1),
            Token::Else,
            Token::Integers(0),
            Token::Fi,
            Token::Semicolon,
            Token::RBrace,
            Token::RBrace,
            Token::Semicolon,
            // cell_at_next_evolution(position : Int) : String {
            Token::ObjectIdentifier(String::from("cell_at_next_evolution")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::LBrace,
            Token::If,
            Token::ObjectIdentifier(String::from("neighbors")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::RParen,
            Token::Eq,
            Token::Integers(3),
            Token::Then,
            Token::StringConstant(String::from("X")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("neighbors")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::RParen,
            Token::Eq,
            Token::Integers(2),
            Token::Then,
            Token::If,
            Token::ObjectIdentifier(String::from("cell")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::RParen,
            Token::Eq,
            Token::StringConstant(String::from("X")),
            Token::Then,
            Token::StringConstant(String::from("X")),
            Token::Else,
            Token::StringConstant(String::from("-")),
            Token::Fi,
            Token::Else,
            Token::StringConstant(String::from("-")),
            Token::Fi,
            Token::Fi,
            Token::RBrace,
            Token::Semicolon,
            // evolve() : SELF_TYPE {
            Token::ObjectIdentifier(String::from("evolve")),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(String::from("position")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::Assign,
            Token::Integers(0),
            Token::In,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(String::from("num")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("num_cells")),
            Token::LParen,
            Token::RParen,
            Token::In,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(String::from("temp")),
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::In,
            Token::LBrace,
            Token::While,
            Token::ObjectIdentifier(String::from("position")),
            Token::Lt,
            Token::ObjectIdentifier(String::from("num")),
            Token::Loop,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("temp")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("temp")),
            Token::Dot,
            Token::ObjectIdentifier(String::from("concat")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("cell_at_next_evolution")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("position")),
            Token::RParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("position")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("position")),
            Token::Plus,
            Token::Integers(1),
            Token::Semicolon,
            Token::RBrace,
            Token::Pool,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("population_map")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("temp")),
            Token::Semicolon,
            Token::SelfValue,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::RParen,
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            // option() : String {
            Token::ObjectIdentifier(String::from("option")),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::LBrace,
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(String::from("num")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Int")),
            Token::In,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\nPlease chose a number:\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t1: A cross\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from(
                "\t2: A slash from the upper left to lower right\n",
            )),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from(
                "\t3: A slash from the upper right to lower left\n",
            )),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t4: An X\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t5: A greater than sign \n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t6: A less than sign\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t7: Two greater than signs\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t8: Two less than signs\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t9: A 'V'\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t10: An inverse 'V'\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t11: Numbers 9 and 10 combined\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t12: A full grid\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t13: A 'T'\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t14: A plus '+'\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t15: A 'W'\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t16: An 'M'\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t17: An 'E'\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t18: A '3'\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t19: An 'O'\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t20: An '8'\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\t21: An 'S'\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("Your choice => ")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("num")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("in_int")),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\n")),
            Token::RParen,
            Token::Semicolon,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(1),
            Token::Then,
            Token::StringConstant(String::from(" XX  XXXX XXXX  XX  ")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(2),
            Token::Then,
            Token::StringConstant(String::from("    X   X   X   X   X    ")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(3),
            Token::Then,
            Token::StringConstant(String::from("X     X     X     X     X")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(4),
            Token::Then,
            Token::StringConstant(String::from("X   X X X   X   X X X   X")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(5),
            Token::Then,
            Token::StringConstant(String::from("X     X     X   X   X    ")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(6),
            Token::Then,
            Token::StringConstant(String::from("    X   X   X     X     X")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(7),
            Token::Then,
            Token::StringConstant(String::from("X  X  X  XX  X      ")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(8),
            Token::Then,
            Token::StringConstant(String::from(" X  XX  X  X  X     ")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(9),
            Token::Then,
            Token::StringConstant(String::from("X   X X X   X  ")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(10),
            Token::Then,
            Token::StringConstant(String::from("  X   X X X   X")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(11),
            Token::Then,
            Token::StringConstant(String::from("X X X X X X X X")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(12),
            Token::Then,
            Token::StringConstant(String::from("XXXXXXXXXXXXXXXXXXXXXXXXX")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(13),
            Token::Then,
            Token::StringConstant(String::from("XXXXX  X    X    X    X  ")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(14),
            Token::Then,
            Token::StringConstant(String::from("  X    X  XXXXX  X    X  ")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(15),
            Token::Then,
            Token::StringConstant(String::from("X     X X X X   X X  ")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(16),
            Token::Then,
            Token::StringConstant(String::from("  X X   X X X X     X")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(17),
            Token::Then,
            Token::StringConstant(String::from("XXXXX   X   XXXXX   X   XXXX")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(18),
            Token::Then,
            Token::StringConstant(String::from("XXX    X   X  X    X   XXXX ")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(19),
            Token::Then,
            Token::StringConstant(String::from(" XX X  XX  X XX ")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(20),
            Token::Then,
            Token::StringConstant(String::from(" XX X  XX  X XX X  XX  X XX ")),
            Token::Else,
            Token::If,
            Token::ObjectIdentifier(String::from("num")),
            Token::Eq,
            Token::Integers(21),
            Token::Then,
            Token::StringConstant(String::from(" XXXX   X    XX    X   XXXX ")),
            Token::Else,
            Token::StringConstant(String::from("                         ")),
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Fi,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::Semicolon,
            Token::RBrace,
            Token::RBrace,
            Token::Semicolon,
            // prompt() : Bool {
            Token::ObjectIdentifier(String::from("prompt")),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("Bool")),
            Token::LBrace,
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(String::from("ans")),
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::In,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from(
                "Would you like to continue with the next generation? \n",
            )),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from(
                "Please use lowercase y or n for your answer [y]: ",
            )),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("ans")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("in_string")),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\n")),
            Token::RParen,
            Token::Semicolon,
            Token::If,
            Token::ObjectIdentifier(String::from("ans")),
            Token::Eq,
            Token::StringConstant(String::from("n")),
            Token::Then,
            Token::BoolConst(false),
            Token::Else,
            Token::BoolConst(true),
            Token::Fi,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::Semicolon,
            Token::RBrace,
            Token::RBrace,
            Token::Semicolon,
            // prompt2() : Bool {
            Token::ObjectIdentifier(String::from("prompt2")),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("Bool")),
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(String::from("ans")),
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::In,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("\n\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from(
                "Would you like to choose a background pattern? \n",
            )),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from(
                "Please use lowercase y or n for your answer [n]: ",
            )),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("ans")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("in_string")),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::If,
            Token::ObjectIdentifier(String::from("ans")),
            Token::Eq,
            Token::StringConstant(String::from("y")),
            Token::Then,
            Token::BoolConst(true),
            Token::Else,
            Token::BoolConst(false),
            Token::Fi,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
            // class Main inherits CellularAutomaton {
            Token::Class,
            Token::TypeIdentifier(String::from("Main")),
            Token::Inherits,
            Token::TypeIdentifier(String::from("CellularAutomaton")),
            Token::LBrace,
            Token::ObjectIdentifier(String::from("cells")),
            Token::Colon,
            Token::TypeIdentifier(String::from("CellularAutomaton")),
            Token::Semicolon,
            // main() : SELF_TYPE {
            Token::ObjectIdentifier(String::from("main")),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::LBrace,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(String::from("continue")),
            Token::Colon,
            Token::TypeIdentifier(String::from("Bool")),
            Token::In,
            Token::LParen,
            Token::Let,
            Token::ObjectIdentifier(String::from("choice")),
            Token::Colon,
            Token::TypeIdentifier(String::from("String")),
            Token::In,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("Welcome to the Game of Life.\n")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from(
                "There are many initial states to choose from. \n",
            )),
            Token::RParen,
            Token::Semicolon,
            Token::While,
            Token::ObjectIdentifier(String::from("prompt2")),
            Token::LParen,
            Token::RParen,
            Token::Loop,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("continue")),
            Token::Assign,
            Token::BoolConst(true),
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("choice")),
            Token::Assign,
            Token::ObjectIdentifier(String::from("option")),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("cells")),
            Token::Assign,
            Token::LParen,
            Token::New,
            Token::TypeIdentifier(String::from("CellularAutomaton")),
            Token::RParen,
            Token::Dot,
            Token::ObjectIdentifier(String::from("init")),
            Token::LParen,
            Token::ObjectIdentifier(String::from("choice")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("cells")),
            Token::Dot,
            Token::ObjectIdentifier(String::from("print")),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::While,
            Token::ObjectIdentifier(String::from("continue")),
            Token::Loop,
            Token::If,
            Token::ObjectIdentifier(String::from("prompt")),
            Token::LParen,
            Token::RParen,
            Token::Then,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("cells")),
            Token::Dot,
            Token::ObjectIdentifier(String::from("evolve")),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("cells")),
            Token::Dot,
            Token::ObjectIdentifier(String::from("print")),
            Token::LParen,
            Token::RParen,
            Token::Semicolon,
            Token::RBrace,
            Token::Else,
            Token::ObjectIdentifier(String::from("continue")),
            Token::Assign,
            Token::BoolConst(false),
            Token::Fi,
            Token::Pool,
            Token::Semicolon,
            Token::RBrace,
            Token::Pool,
            Token::Semicolon,
            Token::SelfValue,
            Token::Semicolon,
            Token::RBrace,
            Token::RParen,
            Token::RParen,
            Token::Semicolon,
            Token::RBrace,
            Token::RBrace,
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
        ];

        assert_eq!(lex(src), result);
    }

    #[test]
    fn hello_world_cl() {
        let src = include_str!("../examples/hello_world.cl");
        let result = vec![
            Token::Class,
            Token::TypeIdentifier("Main".to_string()),
            Token::Inherits,
            Token::TypeIdentifier("IO".to_string()),
            Token::LBrace,
            Token::ObjectIdentifier("main".to_string()),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::SelfType,
            Token::LBrace,
            Token::ObjectIdentifier("out_string".to_string()),
            Token::LParen,
            Token::StringConstant("Hello, World.\n".to_string()),
            Token::RParen,
            Token::RBrace,
            Token::Semicolon,
            Token::RBrace,
            Token::Semicolon,
        ];
        assert_eq!(lex(src), result);
    }

    #[test]
    fn fail_1_cl() {
        let src = include_str!("../examples/fail_lexing/1.cl");
        let result = vec![
            Token::Class,
            Token::TypeIdentifier(String::from("Main")),
            Token::Inherits,
            Token::TypeIdentifier(String::from("IO")),
            Token::LBrace,
            Token::ObjectIdentifier(String::from("main")),
            Token::LParen,
            Token::RParen,
            Token::Colon,
            Token::TypeIdentifier(String::from("Object")),
            Token::LBrace,
            Token::LBrace,
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("hello #world")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("x")),
            Token::Assign,
            Token::Err(ErrorToken::new(
                ErrorKind::UnterminatedStringConstant,
                Some(String::from("Unterminated string constant")),
            )),
            Token::ObjectIdentifier(String::from("out_string")),
            Token::LParen,
            Token::StringConstant(String::from("after error")),
            Token::RParen,
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("y")),
            Token::Assign,
            Token::Err(ErrorToken::new(
                ErrorKind::UnmatchedCloseComment,
                Some(String::from("Unmatched *)")),
            )),
            Token::Semicolon,
            Token::ObjectIdentifier(String::from("z")),
            Token::Assign,
            Token::Err(ErrorToken::new(
                ErrorKind::StringContainsNullCharacter,
                Some(String::from("String contains null character")),
            )),
            Token::Semicolon,
            Token::Err(ErrorToken::new(
                ErrorKind::EofInComment,
                Some(String::from("EOF in comment")),
            )),
        ];

        assert_eq!(lex(src), result);
    }
}
